replicaCount: 1

image: 
  repository: "jitn/spring-boot-helloworld"
  tag: "0.0.1"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 9091

service:
  name: spring-boot-helloworld
  type: NodePort
  port: 9091
  nodePort: 31000
